package drazenvvg.edopis;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Dopis")
public class Dopis implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer dopisID;
   private drazenvvg.edopis.TijeloDrzavneUprave posiljatelj;
   private java.util.Date datumSlanja;
   private drazenvvg.edopis.TijeloDrzavneUprave primatelj;
   private java.lang.String predmet;
   private java.lang.String klasa;
   private java.lang.String urBroj;
   private java.lang.String vezaKlasa;
   private java.lang.String vezaUrBroj;
   private java.lang.String sadrzaj;
   private java.lang.String titulaOdgOsobe;
   private java.lang.String odgovornaOsoba;
   private drazenvvg.edopis.TijeloDrzavneUprave obavijest;

   public Dopis()
   {
   }

   public java.lang.Integer getDopisID()
   {
      return this.dopisID;
   }

   public void setDopisID(java.lang.Integer dopisID)
   {
      this.dopisID = dopisID;
   }

   public drazenvvg.edopis.TijeloDrzavneUprave getPosiljatelj()
   {
      return this.posiljatelj;
   }

   public void setPosiljatelj(drazenvvg.edopis.TijeloDrzavneUprave posiljatelj)
   {
      this.posiljatelj = posiljatelj;
   }

   public java.util.Date getDatumSlanja()
   {
      return this.datumSlanja;
   }

   public void setDatumSlanja(java.util.Date datumSlanja)
   {
      this.datumSlanja = datumSlanja;
   }

   public drazenvvg.edopis.TijeloDrzavneUprave getPrimatelj()
   {
      return this.primatelj;
   }

   public void setPrimatelj(drazenvvg.edopis.TijeloDrzavneUprave primatelj)
   {
      this.primatelj = primatelj;
   }

   public java.lang.String getPredmet()
   {
      return this.predmet;
   }

   public void setPredmet(java.lang.String predmet)
   {
      this.predmet = predmet;
   }

   public java.lang.String getKlasa()
   {
      return this.klasa;
   }

   public void setKlasa(java.lang.String klasa)
   {
      this.klasa = klasa;
   }

   public java.lang.String getUrBroj()
   {
      return this.urBroj;
   }

   public void setUrBroj(java.lang.String urBroj)
   {
      this.urBroj = urBroj;
   }

   public java.lang.String getVezaKlasa()
   {
      return this.vezaKlasa;
   }

   public void setVezaKlasa(java.lang.String vezaKlasa)
   {
      this.vezaKlasa = vezaKlasa;
   }

   public java.lang.String getVezaUrBroj()
   {
      return this.vezaUrBroj;
   }

   public void setVezaUrBroj(java.lang.String vezaUrBroj)
   {
      this.vezaUrBroj = vezaUrBroj;
   }

   public java.lang.String getSadrzaj()
   {
      return this.sadrzaj;
   }

   public void setSadrzaj(java.lang.String sadrzaj)
   {
      this.sadrzaj = sadrzaj;
   }

   public java.lang.String getTitulaOdgOsobe()
   {
      return this.titulaOdgOsobe;
   }

   public void setTitulaOdgOsobe(java.lang.String titulaOdgOsobe)
   {
      this.titulaOdgOsobe = titulaOdgOsobe;
   }

   public java.lang.String getOdgovornaOsoba()
   {
      return this.odgovornaOsoba;
   }

   public void setOdgovornaOsoba(java.lang.String odgovornaOsoba)
   {
      this.odgovornaOsoba = odgovornaOsoba;
   }

   public drazenvvg.edopis.TijeloDrzavneUprave getObavijest()
   {
      return this.obavijest;
   }

   public void setObavijest(drazenvvg.edopis.TijeloDrzavneUprave obavijest)
   {
      this.obavijest = obavijest;
   }

   public Dopis(java.lang.Integer dopisID,
         drazenvvg.edopis.TijeloDrzavneUprave posiljatelj,
         java.util.Date datumSlanja,
         drazenvvg.edopis.TijeloDrzavneUprave primatelj,
         java.lang.String predmet, java.lang.String klasa,
         java.lang.String urBroj, java.lang.String vezaKlasa,
         java.lang.String vezaUrBroj, java.lang.String sadrzaj,
         java.lang.String titulaOdgOsobe, java.lang.String odgovornaOsoba,
         drazenvvg.edopis.TijeloDrzavneUprave obavijest)
   {
      this.dopisID = dopisID;
      this.posiljatelj = posiljatelj;
      this.datumSlanja = datumSlanja;
      this.primatelj = primatelj;
      this.predmet = predmet;
      this.klasa = klasa;
      this.urBroj = urBroj;
      this.vezaKlasa = vezaKlasa;
      this.vezaUrBroj = vezaUrBroj;
      this.sadrzaj = sadrzaj;
      this.titulaOdgOsobe = titulaOdgOsobe;
      this.odgovornaOsoba = odgovornaOsoba;
      this.obavijest = obavijest;
   }

}