package drazenvvg.edopis;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Notfikacija implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Notifikacija ID")
   private java.lang.Integer notifikaciaID;
   @org.kie.api.definition.type.Label(value = "Obavije\u0161teno TDU")
   private drazenvvg.edopis.TijeloDrzavneUprave obavijesten;
   @org.kie.api.definition.type.Label(value = "Datum")
   private java.util.Date datum;

   public Notfikacija()
   {
   }

   public java.lang.Integer getNotifikaciaID()
   {
      return this.notifikaciaID;
   }

   public void setNotifikaciaID(java.lang.Integer notifikaciaID)
   {
      this.notifikaciaID = notifikaciaID;
   }

   public drazenvvg.edopis.TijeloDrzavneUprave getObavijesten()
   {
      return this.obavijesten;
   }

   public void setObavijesten(drazenvvg.edopis.TijeloDrzavneUprave obavijesten)
   {
      this.obavijesten = obavijesten;
   }

   public java.util.Date getDatum()
   {
      return this.datum;
   }

   public void setDatum(java.util.Date datum)
   {
      this.datum = datum;
   }

   public Notfikacija(java.lang.Integer notifikaciaID,
         drazenvvg.edopis.TijeloDrzavneUprave obavijesten,
         java.util.Date datum)
   {
      this.notifikaciaID = notifikaciaID;
      this.obavijesten = obavijesten;
      this.datum = datum;
   }

}