package drazenvvg.edopis;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Notfikacija implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Notfikacija() {
    }

}