package drazenvvg.edopis;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Odbijenica implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Odbijenica ID")
   private java.lang.Integer odbijenicaID;
   @org.kie.api.definition.type.Label("Datum")
   private java.util.Date datum;
   @org.kie.api.definition.type.Label("Dopis")
   private drazenvvg.edopis.Dopis dopis;

   @org.kie.api.definition.type.Label(value = "Obavijesteno TDU")
   private drazenvvg.edopis.TijeloDrzavneUprave obavijesten;

   public Odbijenica()
   {
   }

   public java.lang.Integer getOdbijenicaID()
   {
      return this.odbijenicaID;
   }

   public void setOdbijenicaID(java.lang.Integer odbijenicaID)
   {
      this.odbijenicaID = odbijenicaID;
   }

   public java.util.Date getDatum()
   {
      return this.datum;
   }

   public void setDatum(java.util.Date datum)
   {
      this.datum = datum;
   }

   public drazenvvg.edopis.Dopis getDopis()
   {
      return this.dopis;
   }

   public void setDopis(drazenvvg.edopis.Dopis dopis)
   {
      this.dopis = dopis;
   }

   public drazenvvg.edopis.TijeloDrzavneUprave getObavijesten()
   {
      return this.obavijesten;
   }

   public void setObavijesten(drazenvvg.edopis.TijeloDrzavneUprave obavijesten)
   {
      this.obavijesten = obavijesten;
   }

   public Odbijenica(java.lang.Integer odbijenicaID, java.util.Date datum,
         drazenvvg.edopis.Dopis dopis,
         drazenvvg.edopis.TijeloDrzavneUprave obavijesten)
   {
      this.odbijenicaID = odbijenicaID;
      this.datum = datum;
      this.dopis = dopis;
      this.obavijesten = obavijesten;
   }

}